spring:
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

debug: true

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG

jwt:
  access-token-valid-time: ${JWT_ACCESS_TIME}
  prefix: Bearer
  header: Authorization
  secret-key: ${JWT_SECRET}